services:
  - type: web
    name: banking-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn banking_app.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: banking_app.settings
      - key: SECRET_KEY
        value: your-secret-key
